config/routes.rb
Rails.application.routes.draw do
  devise_for :models

  root to: 'home#index'
  get '/search', to: 'home#search'


  resources :model_posts do
    resources :likes , dependent: :destroy
    resources :comments ,module: :model_posts
  end

  resources :comments  do
    resources :comments ,module: :comments
  end
  resources :uploads


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :model
  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable

  delegate :email , to: :model


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :model_post
  belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :model_posts
  has_many :likes, dependent: :destroy
  has_many :uploads
  has_many :comments
  validates :email, presence:  true
  validates :name, presence:  true , uniqueness: true
end

app/models/model_post.rb
class ModelPost < ApplicationRecord
  belongs_to :model
  has_many :likes, dependent: :destroy

  delegate :email , to: :model
  delegate :name , to: :model

  has_many :comments, as: :commentable
end

app/models/upload.rb
class Upload < ApplicationRecord


  include FileUploader.attachment(:image)

  belongs_to :model
  validates :tof ,acceptance: { accept: ['video' , 'image' , 'pdf'] }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
     @model_posts = ModelPost.all

  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!")
    else

      @results = ModelPost.joins(:model).all.where('title LIKE :search OR email LIKE :search ', search: "%"+  params[:search] +"%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/model_posts_helper.rb
module ModelPostsHelper
end

app/helpers/my_photos_helper.rb
module MyPhotosHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_photo_helper.rb
module PostPhotoHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asina</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'others/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/others/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>

          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>

          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
          <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg" alt="Workflow">
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="/" class="text-gray-300 hover:bg-gray-700 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Home</a>
            <%if !model_signed_in? %>

              <%= link_to "Log in ", model_session_path  , class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>

              <%= link_to "Sign up", "/models/sign_up" , class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>


            <%end%>
           <%if model_signed_in? %>
              <%= link_to "sign_out", destroy_model_session_path, method: :delete, class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>

              <%= link_to "Post_Photo",new_model_post_path , class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>

              <%= link_to "My Photos",model_posts_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>

              <%= link_to "My Uploads",uploads_path, class: 'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium'%>

          <%end%>
            <%=form_tag(search_path, :method => "get", class: '')  do%>
            <%= text_field_tag(:search , params[:search]) %>
              <%= submit_tag("Search")%>
            <%end %>

          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
            <button type="button" class="bg-gray-800 flex text-sm  rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>


        </div>
      </div>
    </div>
  </div>


</nav>

app/views/replays/_replays.html.erb
<% commentable.comments.each do |comment|%>
  <div class="flex-col m-2 text-gray-900 text-md font-serif rounded-2xl bg-gray-200 ">
    <div class="flex-col ">

      <div class="flex ">
        <img src="https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png" alt="image" class=" w-10 h-10 rounded-lg object-cover bg-gray-100">

        <p class="text-md text-gray-700 font-serif m-1"> replayed by: </p>
        <p class="text-md text-gray-900 font-serif m-1"><%= comment.email %></p>

      </div>

      <div class="m-1 p-2 grid-cols-3 ">
        <div class="col-span-2 bg-gray-50 rounded-lg">
          <p class="ml-1"> <%= comment.body %></p>
        </div>

      </div >
      <div class=" flex m-1 pl-2">
        <div class="pl-2">like </div>
        <div class="pl-2 mt-0.5 text-sm font-sans"> 25likes </div>

      </div>
    </div>

  </div>
<% end %>