config/routes.rb
Rails.application.routes.draw do
  devise_for :models

  root to: 'home#index'
  get '/search', to: 'home#search'


  resources :model_posts do
    resources :likes , dependent: :destroy
    resources :comments ,module: :model_posts
  end

  resources :comments  do
    resources :comments ,module: :comments
  end
  resources :uploads


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :model
  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable

  delegate :email , to: :model


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :model_post
  belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :model_posts
  has_many :likes, dependent: :destroy
  has_many :uploads
  has_many :comments
  validates :email, presence:  true
  validates :name, presence:  true , uniqueness: true
end

app/models/model_post.rb
class ModelPost < ApplicationRecord
  belongs_to :model
  has_many :likes, dependent: :destroy

  delegate :email , to: :model
  delegate :name , to: :model

  has_many :comments, as: :commentable
end

app/models/upload.rb
class Upload < ApplicationRecord


  include FileUploader.attachment(:image)

  belongs_to :model
  validates :tof ,acceptance: { accept: ['video' , 'image' , 'pdf'] }
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController<CommentsController
  before_action :set_commentable
  private
  def set_commentable
    @commentable =Comment.find(params[:comment_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_model!

  def index
    @comment=@commentable.comments.all
  end
  def new
    @comment=@commentable.comments.new
  end

  def create

    @comment = @commentable.comments.new(get_params)
    @comment.model = current_model
    if @comment.save

      redirect_to root_path
    else
      render :new ,alert:"something wrong"
    end
  end


  private

  def get_params
    params.require(:comment).permit(:body ,:commentable_type )
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
     @model_posts = ModelPost.all

  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!")
    else

      @results = ModelPost.joins(:model).all.where('title LIKE :search OR email LIKE :search ', search: "%"+  params[:search] +"%")
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  # before_action :already_liked? ,only: [:create]
  def create
    if  already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @model_post.likes.create(model_id: current_model.id)
    end
    redirect_to root_path(@model_post)

  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to root_path(@model_post)
  end

  private

  def find_post
    @model_post = ModelPost.find(params[:model_post_id])
  end

  def already_liked?
    Like.where(model_id: current_model.id, model_post_id:
      params[:model_post_id]).exists?
  end
  def find_like
    @like = @model_post.likes.find(params[:id])
  end
end

app/controllers/model_posts/comments_controller.rb
class ModelPosts::CommentsController<CommentsController
  before_action :set_commentable
  private
  def set_commentable
    @commentable = ModelPost.find(params[:model_post_id])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = current_model.uploads
  end

  def new
    @new_upload = Upload.new
  end

  def create
    @new_upload = current_model.uploads.new(upload_params)
    if @new_upload.save

      redirect_to uploads_path
    else
      render :index
    end
  end


  private

  def upload_params
    params.require(:upload).permit(:title,:tof,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/model_posts_helper.rb
module ModelPostsHelper
end

app/helpers/my_photos_helper.rb
module MyPhotosHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_photo_helper.rb
module PostPhotoHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<h3 class="text-gray-700 pl-10 font-serif text-3xl font-semibold">Comments</h3>


<div class="grid pl-12 m-1 grid-cols-3 ">



  <div class="bg-gray-100 rounded-2xl ">
    <% commentable.comments.each do |comment|%>
      <div class="flex-col m-2 text-gray-900 text-md font-serif rounded-2xl bg-gray-200 ">
        <div class="flex-col ">

          <div class="flex ">
            <img src="https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png" alt="image" class=" w-10 h-10 rounded-lg object-cover bg-gray-100">

            <p class="text-md text-gray-700 font-serif m-1"> Comment by: </p>
            <p class="text-md text-gray-900 font-serif m-1"><%= comment.email %></p>

          </div>

          <div class="m-1 p-2 grid-cols-3 ">
            <div class="col-span-2 bg-gray-50 rounded-lg">
              <p class="ml-1"> <%= comment.body %></p>
            </div>

          </div >
          <div class=" flex m-1 pl-2">
            <div class="pl-2">like </div>
            <div class="pl-2 mt-0.5 text-sm font-sans"> 25likes </div>
            <div class="pl-2 text-indigo-700"> <%= link_to "replay", new_comment_comment_path(comment.id) %> </div>

          </div>
          <%unless Comment.nil?%>
          <div class="m-2 px-8 pt-2"><%= render partial: "replays/replays" , locals: { commentable: comment} %></div>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

</div>

app/views/comments/index.html.erb
<h3>Comments</h3>

<div>

</div>

app/views/comments/new.html.erb
<div class="flex justify-center">
  <% flash.each do |type, alert| %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <%= alert %>
    </div>
  <% end %>
</div>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
        Comments
      </h2>
    </div>

    <%= form_with model: [@commentable, Comment.new] , local:true , html: { class:"mt-8 space-y-6"} do |form| %>
      <%=form.hidden_field :commentable_type ,value:"ModelPost"%>

      <%= form.label :body, "Comment:" %>
      <%= form.text_field :body, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.submit "Post" ,class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>

    <% end %>


  </div>
</div>