config/routes.rb
Rails.application.routes.draw do
  devise_for :models

  root to: 'home#index'
  get '/search', to: 'home#search'


  resources :model_posts do
    resources :likes , dependent: :destroy
    resources :comments ,module: :model_posts
  end

  resources :comments  do
    resources :comments ,module: :comments
  end
  resources :uploads


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :model
  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable

  delegate :email , to: :model


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :model_post
  belongs_to :model
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :model_posts
  has_many :likes, dependent: :destroy
  has_many :uploads
  has_many :comments
  validates :email, presence:  true
  validates :name, presence:  true , uniqueness: true
end

app/models/model_post.rb
class ModelPost < ApplicationRecord
  belongs_to :model
  has_many :likes, dependent: :destroy

  delegate :email , to: :model
  delegate :name , to: :model

  has_many :comments, as: :commentable
end

app/models/upload.rb
class Upload < ApplicationRecord


  include FileUploader.attachment(:image)

  belongs_to :model
  validates :tof ,acceptance: { accept: ['video' , 'image' , 'pdf'] }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
     @model_posts = ModelPost.all

  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!")
    else

      @results = ModelPost.joins(:model).all.where('title LIKE :search OR email LIKE :search ', search: "%"+  params[:search] +"%")
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  # before_action :already_liked? ,only: [:create]
  def create
    if  already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @model_post.likes.create(model_id: current_model.id)
    end
    redirect_to root_path(@model_post)

  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to root_path(@model_post)
  end

  private

  def find_post
    @model_post = ModelPost.find(params[:model_post_id])
  end

  def already_liked?
    Like.where(model_id: current_model.id, model_post_id:
      params[:model_post_id]).exists?
  end
  def find_like
    @like = @model_post.likes.find(params[:id])
  end
end

app/controllers/model_posts/comments_controller.rb
class ModelPosts::CommentsController<CommentsController
  before_action :set_commentable
  private
  def set_commentable
    @commentable = ModelPost.find(params[:model_post_id])
  end
end

app/controllers/model_posts_controller.rb
class ModelPostsController < ApplicationController
  before_action :authenticate_model!
  before_action :set_photo ,only: [:edit,:update ,:destroy ,:show]
  def index
    @model_posts = current_model.model_posts
  end

  def new
  end
  def show

  end
  def create
    @new_post = current_model.model_posts.new(post_params)
    if @new_post.save

      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @model_post.update(get_params)

      redirect_to model_posts_path
      puts("looooooooooooooooooooooooooooooooool")
    else
      render :edit
    end
  end

  def destroy
    @model_post.destroy
    redirect_to model_posts_path
  end




  private
  def get_params
    params.require(:model_post).permit(:title,:content,:image)
  end
  def post_params
    params.permit(:title,:content,:image)
  end

  def set_photo
    @model_post = ModelPost.find(params[:id])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = current_model.uploads
  end

  def new
    @new_upload = Upload.new
  end

  def create
    @new_upload = current_model.uploads.new(upload_params)
    if @new_upload.save

      redirect_to uploads_path
    else
      render :index
    end
  end


  private

  def upload_params
    params.require(:upload).permit(:title,:tof,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/model_posts_helper.rb
module ModelPostsHelper
end

app/helpers/my_photos_helper.rb
module MyPhotosHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/post_photo_helper.rb
module PostPhotoHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/model_posts/_model_post.html.erb
<div class="p-10">
  <!--Card 1-->
  <div class="max-w-sm rounded overflow-hidden shadow-lg">
    <img class="object-fill h-48 w-34 w-full  lazy"  src="<%=model_post.image %>" alt="Mountain">
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2"><%= model_post.title %></div>
      <p class="text-gray-700 text-base">
        <%= model_post.content %>
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <%= model_post.name %> </span>
      <% if current_page?(:controller => 'model_posts', :action => 'index') %>

        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "edit" , edit_model_post_path(model_post) %></span>

        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-red-700 mr-2 mb-2"><%= link_to "delete" ,model_post_path(model_post), method: :delete%></span>

    <%end %>
      <%if model_signed_in? %>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <% pre_like = model_post.likes.find { |like| like.model_id == current_model.id} %>
        <% if pre_like %>
           <%= button_to 'Unlike', model_post_like_path(model_post, pre_like), method: :delete %>
        <% else %>
          <%= button_to 'Like', model_post_likes_path(model_post), method: :post %>
        <% end %>
       </span>
      <%end%>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <%= model_post.likes.count %> <%= (model_post.likes.count) == 1 ? 'Like' : 'Likes'%> </span>


      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <%= link_to "Show::Comments",model_post_path(model_post.id)%></span>

    </div>
  </div>
</div>

app/views/model_posts/edit.html.erb
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
        EDIT POST
      </h2>
    </div>

    <%= form_with model: @model_post , html: { class:"mt-8 space-y-6"} do |form| %>
      <%= form.label :title, "Title:" %>
      <%= form.text_field :title, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.label :content, "content:" %>
      <%= form.text_area :content, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.label :image, "image:" %>
      <%= form.text_field :image, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.submit "Update" ,class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>

    <% end %>


  </div>
</div>

app/views/model_posts/index.html.erb
<h1>HOME</h1>
<%if model_signed_in? %>

  <%= current_model.email %>

<%end%>

<%#= render @model_posts, partial: "home/cards",collection: true , locals: {object: @model_posts} %>



<div class="grid grid-cols-4">
  <%= render @model_posts %>
</div>

app/views/model_posts/new.html.erb
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
        POST YOUR PHOTO
      </h2>
    </div>

    <%= form_with model: @new_post , url: model_posts_path , html: { class:"mt-8 space-y-6"} do |form| %>
      <%= form.label :title, "Title:" %>
      <%= form.text_field :title, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.label :content, "content:" %>
      <%= form.text_area :content, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.label :image, "image:" %>
      <%= form.text_field :image, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>

      <%= form.submit "Post" ,class:"group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>

    <% end %>


  </div>
</div>

app/views/model_posts/show.html.erb
<div class="p-10">
  <!--Card 1-->
  <div class="max-w-sm rounded overflow-hidden shadow-lg">
    <img class="object-fill h-48 w-34 w-full  lazy"  src="<%=@model_post.image %>" alt="Mountain">
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2"><%= @model_post.title %></div>
      <p class="text-gray-700 text-base">
        <%= @model_post.content %>
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <%= @model_post.email %> </span>
      <% if current_page?(:controller => 'model_posts', :action => 'index') %>

        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "edit" , edit_model_post_path(@model_post) %></span>

        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-red-700 mr-2 mb-2"><%= link_to "delete" ,model_post_path(@model_post), method: :delete%></span>

      <%end %>
      <%if model_signed_in? %>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <% pre_like = @model_post.likes.find { |like| like.model_id == current_model.id} %>
        <% if pre_like %>
           <%= button_to 'Unlike', model_post_like_path(@model_post, pre_like), method: :delete %>
        <% else %>
          <%= button_to 'Like', model_post_likes_path(@model_post), method: :post %>
        <% end %>
       </span>
      <%end%>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"> <%= @model_post.likes.count %> <%= (@model_post.likes.count) == 1 ? 'Like' : 'Likes'%> </span>

      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">   <%= link_to "Create A Comment", new_model_post_comment_path(@model_post.id)%> </span>

    </div>
  </div>
</div>

 <% unless Comment.nil?  %>


    <%= render partial: "comments/comment" , locals: { commentable: @model_post} %>


 <%end%>